### ISSUE TITLE
Buat Activity Diagram tentang project kita 

### ISSUE THREAD

**Issue by Adul28** [Adul28/PROJECT-REKWEB---PRESENSI-DAN-BOOKING-CUTI-BERBASIS-WEB-APPLICATION#5]
Semangaaat ... Kelompok 1 pasti bisa !!!

**Comment by gunawandul** [comment]
[Activity Diagram.pptx](https://github.com/Adul28/PROJECT-REKWEB---PRESENSI-DAN-BOOKING-CUTI-BERBASIS-WEB-APPLICATION/files/543471/Activity.Diagram.pptx)
